version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: demetra-postgres
    environment:
      POSTGRES_USER: arsen
      POSTGRES_PASSWORD: root
      POSTGRES_DB: demetra_db
    ports:
      - "5432:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: demetra-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
